### ISSUE TITLE
Validator is losing state, Always nulll when trying to shut it down. There is no simple way to shut down the Cash Accepter

### ISSUE THREAD

**Issue by ErnestMushinge** [PyramidTechnologies/netPyramid-RS-232#8]
- [ ] When the Cash Acceptor is started, shutting down does not work. Implemented a function to shut down the Cash Acceptor but the Validator is always null. It looks like the Validator runs on a different thread which makes it impossible to access the running instance to shut it down.

**Comment by corytodd** [comment]
The main loop should not be manually stopped and started. Instead, use the pause and resume API.

https://github.com/PyramidTechnologies/netPyramid-RS-232/blob/master/Apex7000_BillValidator/ApexValidator.cs#L138

Pay close attention to the notes on that function because they explain that pausing/stopping the acceptor immediately is not possible. This is due to the way this protocol is designed.

**Comment by ErnestMushinge** [comment]
@corytodd Thank you Cory like you mentioned I will go ahead and try activating the escrow mode.
